schemaVersion: 2.2.0
metadata:
  generateName: ${{values.artifact_id}}
components:
  - name: development-tooling
    attributes:
      pod-overrides:
        metadata:
          annotations:
            io.kubernetes.cri-o.Devices: "/dev/fuse,/dev/net/tun"
        spec:
          hostUsers: false
      container-overrides: 
        securityContext:
          procMount: Unmasked
    container:
      image: registry.redhat.io/devspaces/udi-rhel9:latest
      env:
        - name: USE_JAVA21
          value: "true"
        - name: DOCKER_HOST
          value: "unix:///tmp/storage-run-1000/podman/podman.sock"
        - name: TESTCONTAINERS_RYUK_DISABLED
          value: "true"
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
        - name: MAVEN_OPTS
          value: "-Dmaven.repo.local=/home/user/.m2/repository"
        - name: HOST_USERS
          value: "false"
      memoryLimit: 4Gi
      cpuLimit: 2500m
      volumeMounts:
        - name: m2
          path: /home/user/.m2
{%- if values.verify_commits == 'enabled' %}
        - name: home
          path: /projects/home
{%- endif %}
      endpoints:
        - name: quarkus-dev
          targetPort: 8080
          exposure: public
          secure: false
          protocol: https
        - name: debug
          targetPort: 5005
          exposure: none
          secure: false
          protocol: tcp
        - name: tests
          targetPort: 8081
          exposure: none
          secure: false
          protocol: tcp
  - name: m2
    volume:
      size: 1G
commands:
  - id: package
    exec:
      label: "1. Package the application"
      component: development-tooling
      commandLine: "./mvnw package"
      group:
        kind: build
        isDefault: true
  
  - id: start-dev
    exec:
      label: "2. Start Development mode (Hot reload + debug)"
      component: development-tooling
      commandLine: "./mvnw compile quarkus:dev"
      group:
        kind: run
        isDefault: true

  - id: quarkus-devservices-config
    exec:
      label: "Quarkus config"
      component: development-tooling
      commandLine: "sed -i \"s/SOMETHING/$(oc get dw --sort-by=.metadata.creationTimestamp -o jsonpath='{.items[?(@.status.phase==\"Starting\")].metadata.name}')/\" /projects/*/src/main/resources/application.properties"
      group:
        kind: run
        isDefault: true

  - id: install-quarkus
    exec:
      label: "Quarkus install"
      component: development-tooling
      commandLine: "curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/ && curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio"
  - id: podman-start
    exec:
      label: "Podman start"
      component: development-tooling
      commandLine: "podman system service --time=0 &"

events:
  postStart:
    - quarkus-devservices-config
    - install-quarkus
    - podman-start